#############################################################################
# Makefile for building: mythspotify
# Generated by qmake (2.01a) (Qt 4.6.3) on: Mon Jul 25 22:26:48 2011
# Project:  mythspotify.pro
# Template: subdirs
# Command: /usr/bin/qmake -unix -o Makefile mythspotify.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-mythspotify \
		sub-theme \
		sub-i18n

mythspotify/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) mythspotify/ || $(MKDIR) mythspotify/ 
	cd mythspotify/ && $(QMAKE) /root/mythtv/mythplugins/mythspotify/mythspotify/mythspotify.pro -unix -o $(MAKEFILE)
sub-mythspotify-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) mythspotify/ || $(MKDIR) mythspotify/ 
	cd mythspotify/ && $(QMAKE) /root/mythtv/mythplugins/mythspotify/mythspotify/mythspotify.pro -unix -o $(MAKEFILE)
sub-mythspotify: mythspotify/$(MAKEFILE) FORCE
	cd mythspotify/ && $(MAKE) -f $(MAKEFILE)
sub-mythspotify-make_default: mythspotify/$(MAKEFILE) FORCE
	cd mythspotify/ && $(MAKE) -f $(MAKEFILE) 
sub-mythspotify-make_first: mythspotify/$(MAKEFILE) FORCE
	cd mythspotify/ && $(MAKE) -f $(MAKEFILE) first
sub-mythspotify-all: mythspotify/$(MAKEFILE) FORCE
	cd mythspotify/ && $(MAKE) -f $(MAKEFILE) all
sub-mythspotify-clean: mythspotify/$(MAKEFILE) FORCE
	cd mythspotify/ && $(MAKE) -f $(MAKEFILE) clean
sub-mythspotify-distclean: mythspotify/$(MAKEFILE) FORCE
	cd mythspotify/ && $(MAKE) -f $(MAKEFILE) distclean
sub-mythspotify-install_subtargets: mythspotify/$(MAKEFILE) FORCE
	cd mythspotify/ && $(MAKE) -f $(MAKEFILE) install
sub-mythspotify-uninstall_subtargets: mythspotify/$(MAKEFILE) FORCE
	cd mythspotify/ && $(MAKE) -f $(MAKEFILE) uninstall
theme/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) theme/ || $(MKDIR) theme/ 
	cd theme/ && $(QMAKE) /root/mythtv/mythplugins/mythspotify/theme/theme.pro -unix -o $(MAKEFILE)
sub-theme-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) theme/ || $(MKDIR) theme/ 
	cd theme/ && $(QMAKE) /root/mythtv/mythplugins/mythspotify/theme/theme.pro -unix -o $(MAKEFILE)
sub-theme: theme/$(MAKEFILE) FORCE
	cd theme/ && $(MAKE) -f $(MAKEFILE)
sub-theme-make_default: theme/$(MAKEFILE) FORCE
	cd theme/ && $(MAKE) -f $(MAKEFILE) 
sub-theme-make_first: theme/$(MAKEFILE) FORCE
	cd theme/ && $(MAKE) -f $(MAKEFILE) first
sub-theme-all: theme/$(MAKEFILE) FORCE
	cd theme/ && $(MAKE) -f $(MAKEFILE) all
sub-theme-clean: theme/$(MAKEFILE) FORCE
	cd theme/ && $(MAKE) -f $(MAKEFILE) clean
sub-theme-distclean: theme/$(MAKEFILE) FORCE
	cd theme/ && $(MAKE) -f $(MAKEFILE) distclean
sub-theme-install_subtargets: theme/$(MAKEFILE) FORCE
	cd theme/ && $(MAKE) -f $(MAKEFILE) install
sub-theme-uninstall_subtargets: theme/$(MAKEFILE) FORCE
	cd theme/ && $(MAKE) -f $(MAKEFILE) uninstall
i18n/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) i18n/ || $(MKDIR) i18n/ 
	cd i18n/ && $(QMAKE) /root/mythtv/mythplugins/mythspotify/i18n/i18n.pro -unix -o $(MAKEFILE)
sub-i18n-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) i18n/ || $(MKDIR) i18n/ 
	cd i18n/ && $(QMAKE) /root/mythtv/mythplugins/mythspotify/i18n/i18n.pro -unix -o $(MAKEFILE)
sub-i18n: i18n/$(MAKEFILE) FORCE
	cd i18n/ && $(MAKE) -f $(MAKEFILE)
sub-i18n-make_default: i18n/$(MAKEFILE) FORCE
	cd i18n/ && $(MAKE) -f $(MAKEFILE) 
sub-i18n-make_first: i18n/$(MAKEFILE) FORCE
	cd i18n/ && $(MAKE) -f $(MAKEFILE) first
sub-i18n-all: i18n/$(MAKEFILE) FORCE
	cd i18n/ && $(MAKE) -f $(MAKEFILE) all
sub-i18n-clean: i18n/$(MAKEFILE) FORCE
	cd i18n/ && $(MAKE) -f $(MAKEFILE) clean
sub-i18n-distclean: i18n/$(MAKEFILE) FORCE
	cd i18n/ && $(MAKE) -f $(MAKEFILE) distclean
sub-i18n-install_subtargets: i18n/$(MAKEFILE) FORCE
	cd i18n/ && $(MAKE) -f $(MAKEFILE) install
sub-i18n-uninstall_subtargets: i18n/$(MAKEFILE) FORCE
	cd i18n/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: mythspotify.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -unix -o Makefile mythspotify.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -unix -o Makefile mythspotify.pro

qmake_all: sub-mythspotify-qmake_all sub-theme-qmake_all sub-i18n-qmake_all FORCE

make_default: sub-mythspotify-make_default sub-theme-make_default sub-i18n-make_default FORCE
make_first: sub-mythspotify-make_first sub-theme-make_first sub-i18n-make_first FORCE
all: sub-mythspotify-all sub-theme-all sub-i18n-all FORCE
clean: sub-mythspotify-clean sub-theme-clean sub-i18n-clean FORCE
distclean: sub-mythspotify-distclean sub-theme-distclean sub-i18n-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-mythspotify-install_subtargets sub-theme-install_subtargets sub-i18n-install_subtargets FORCE
uninstall_subtargets: sub-mythspotify-uninstall_subtargets sub-theme-uninstall_subtargets sub-i18n-uninstall_subtargets FORCE

sub-mythspotify-check: mythspotify/$(MAKEFILE)
	cd mythspotify/ && $(MAKE) check
sub-theme-check: theme/$(MAKEFILE)
	cd theme/ && $(MAKE) check
sub-i18n-check: i18n/$(MAKEFILE)
	cd i18n/ && $(MAKE) check
check: sub-mythspotify-check sub-theme-check sub-i18n-check

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

